### PR TITLE
fix: prevent logs pollution for recursive matching algorithm

### PR DESCRIPTION
**Pull request by csviri**

### CODE REVIEW

**Review by metacosm — COMMENTED** [review]
I'm not sure what this change is supposed to fix. How is changing the logging level addressing any recursion?

**Comment by csviri** [comment]
> I'm not sure what this change is supposed to fix. How is changing the logging level addressing any recursion?

So it is not polluting the logs on Debug level.

**Comment by metacosm** [comment]
OK, so I think this needs a better wording on the commit message then :)

**Comment by csviri** [comment]
> OK, so I think this needs a better wording on the commit message then :)

Tried my best, changed the title. But feel free to change it :)

**Review by metacosm — APPROVED** [review]

**Pull request merged**
