### PR TITLE
docs: read only sample link

### PR DESCRIPTION
**Pull request by csviri**

### CODE REVIEW

**Comment by csviri** [comment]
will try to turn off opeshift ci for the project

**Comment by metacosm** [comment]
> will try to turn off opeshift ci for the project

Why?

**Review by metacosm — APPROVED** [review]

**Comment by csviri** [comment]
itt adds people to review the PR's, not sure based on what :)

**Comment by metacosm** [comment]
> itt adds people to review the PR's, not sure based on what :)

Then it would be better to figure out what it does before turning it off… 😄 
This is part of the organisation automation so it'd be nicer if we played by the same rules.

**Pull request merged**
